### ISSUE TITLE
Spring boot version and spring cloud version does not match

### ISSUE THREAD

**Issue by stonerich** [spring-guides/gs-service-registration-and-discovery#22]
The latest change upgraded the spring boot version, but the spring cloud release train is still set to Finchley.SR2 that does not work with the 2.2.1 version of spring boot.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-service-registration-and-discovery/commit/d132b271d8c0bd100a5a17adea48f4503a4d76c7.
