### ISSUE TITLE
Update confusing docs, as the @EnableDiscoveryClient is no longer required

### ISSUE THREAD

**Issue by havinhphu188** [spring-guides/gs-service-registration-and-discovery#25]
In the section Talking to the Registry, there is a mention of @EnableDiscoveryClient. But it causes confusion because there is no use of @EnableDiscoveryClient on the entire of the getting-started project. 

As mention in https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_commons_common_abstractions.html , @EnableDiscoveryClient is no longer required, hence should be removed from GS

**Comment by Buzzardo** [comment]
We have this guide marked for a rewrite. I'll leave this open as one of the things to check on when it is rewritten.

**Comment by robertmcnees** [comment]
Closing this issue as a rewrite was done in PR #33. Please feel free to test the guide and open a new issue if this problem persists.
