### ISSUE TITLE
Cannot clone repository - error: invalid path 'complete/eureka-service/:q

### ISSUE THREAD

**Issue by jeremywickham** [spring-guides/gs-service-registration-and-discovery#30]
Going through a tutorial and I cannot clone the repository, it appears that a file has been renamed to :q

**Comment by PVerschueren107** [comment]
I created a PR to remove the :q file.  I also believe someone made a mistake doing a :q out of VI(M) and renaming the file instead.

**Comment by gejarajanbrg** [comment]
Still unable to checkout because of the issue, any update on the changes?

**Comment by Buzzardo** [comment]
Fixed in https://github.com/spring-guides/gs-service-registration-and-discovery/pull/31
