### ISSUE TITLE
error: deploy discovery service to cloud foundry

### ISSUE THREAD

**Issue by betht1220** [spring-guides/gs-service-registration-and-discovery#5]
I've "mvn clean package", deployed the discovery service using a manifest.yml, and
  run into this runtime error (cf a shows the app starts, but logs has error)
  
  I've tried to fix the bug, but so far no result.
  Appreciate your pointers.

```
manifest.yml
     name: discovery-service
     memory: 512M
     instances: 1
     path: ./target/eureka-service-0.0.1-SNAPSHOT.jar
     buildpack: java_buildpack
     disk_quota: 1024M
     host: event-stream-discovery-service
    domain: local.pcfdev.io
```

```
Error:
Caused by: javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Error reading configuration file
```

**Comment by dsyer** [comment]
That's a weird one. Looks like a problem with the JVM in your buildpack. Is it customized in some way?

**Comment by betht1220** [comment]
I've deployed on pcfdev (pcfdev-v0.461.0.vbox), and following buildpack.
java_buildpack          1          true      false    java-buildpack-offline-v3.13.zip

Deployment successful with discovery service spring boot 1.3.3
Deployment error with discovery service spring boot 1.5.6RELEASE

I use start.spring.io with 1.5.10 to configure for a discovery service, and got the same error

Thanks Dave
