### ISSUE TITLE
This should be marked as "Only works with Up to JDK 1.8"

### ISSUE THREAD

**Issue by jackdpeterson** [spring-guides/gs-service-registration-and-discovery#6]
The documentation in the repository does not work with Java 9 out of the box. 
A quick googling leads one to the following article https://blog.frankel.ch/migrating-to-java-9/1/ which is fairly informative on the various issues one will encounter when first getting started using Java 9 and an initial foray into the spring ecosystem. Fixing the guides to be either Java 9 compatible would be nice. BTW, why can't the dependency management system just resolve for JAXB? This is something that NPM does just fine in JS land, and composer does in PHP land -- or at least composer would complain about missing X extension ... which seems somewhat synonymous with the removal of EE libraries from SE 9.

Alternatively, indicating that getting to Java 9 is going to have the following X steps that need to be taken for each guide would be helpful.

Thanks!

**Comment by Buzzardo** [comment]
We have this guide marked for a rewrite.  I'll leave this open as one of the things to check on when it is rewritten.

We are trying to get everything to work with Java 17, but we need to rewrite this guide to fix other issues, too.

**Comment by robertmcnees** [comment]
Closing this issue as a rewrite was done in PR #33. Please feel free to test the guide and open a new issue if this problem persists.
