### ISSUE TITLE
java.lang.NoClassDefFoundError: com/netflix/config/ConfigurationManager

### ISSUE THREAD

**Issue by lyntann** [spring-guides/gs-service-registration-and-discovery#8]
is there anybody met the same problem while run "EurekaServiceApplication.java", it throws error below:
java.lang.NoClassDefFoundError: com/netflix/config/ConfigurationManager

**Comment by Buzzardo** [comment]
We have this guide marked for a rewrite.  I'll leave this open as one of the things to check on when it is rewritten.

**Comment by robertmcnees** [comment]
Closing this issue as a rewrite was done in PR #33. Please feel free to test the guide and open a new issue if this problem persists.
